---
title: Matthew Bischoff
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/uploads/matthew.jpg"
permalink: "/:title/"
url: https://matthewbischoff.com
paginate: 5
baseurl: 
author:
  name: Matthew Bischoff
  url: https://twitter.com/mb
  email: mb@matthewbischoff.com
  twitter: mb
description: Hey, I’m <a href="https://matthewbischoff.com/about/">Matt</a>. I write
  software in New York.
logo: "/uploads/matthew.jpg"
version: 0.4
license:
  text: Some rights reserved
  url: http://creativecommons.org/licenses/by-sa/4.0/
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-feed
- jekyll-redirect-from
twitter:
  username: mb
facebook:
  publisher: https://www.facebook.com/matthewbischoff
  admins: https://www.facebook.com/matthewbischoff
google_site_verification: XK_j6lkDAd8qOhIn4-2eS2BIJuQyRp4D_gxjpR65wUM
sass:
  sass_dir: _sass
  style: compressed
repository: mattbischoff/matthewbischoff.com
